### ISSUE TITLE
erreur "Failed refreshing cookie" à la validation de la config

### ISSUE THREAD

**Issue by ChtiKev** [laurent-martin/hass_int_toutsurmoneau#5]
Bonjour,

Déjà merci pour cette intégration.

J'ai une erreur "Unexpected error" à la validation de la config de l'intégration.
En regardant les logs j'ai trouvé ceci.

> 2023-04-21 20:48:36.255 ERROR (MainThread) [custom_components.portail_eau_fr.config_flow] An exception ocurred: Failed refreshing cookie
Traceback (most recent call last):
  File "/config/custom_components/portail_eau_fr/config_flow.py", line 81, in async_step_user
    "contract": (await client.async_contracts())[0],
  File "/usr/local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 198, in async_contracts
    contract_list = await self._async_call_api(API_ENDPOINT_CONTRACT)
  File "/usr/local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 168, in _async_call_api
    raise ClientError('Failed refreshing cookie')
toutsurmoneau.errors.ClientError: Failed refreshing cookie

Quand je valide ma connexion sur le site https://www.toutsurmoneau.fr/mon-compte-en-ligne, j'arrive ensuite sur https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne.

Merci

**Comment by laurent-martin** [comment]
Avez vous essayé en mettant https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne comme URL initial ?

Si vous avez python d'installé sur une machine, il est possible de tester ainsi:

Voir: https://github.com/laurent-martin/py-mon-eau

```bash
pip install toutsurmoneau

toutsurmoneau --url https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne --username _username_ --password _password_ --debug --execute contracts
```

Il est possible que les divers sites n'utilisent pas la meme version du code, je vais regarder..

**Comment by ChtiKev** [comment]
En passant par la commande directe je n'ai pas de problème. La commande
récupère bien les informations de mon contrat en utilisant l'adresse
https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne. En
revanche, si j'essaie avec l'adresse
https://www.toutsurmoneau.fr/mon-compte-en-ligne ça ne fonctionne pas et je
retrouve bien l'erreur du cookie.

Du coup j'ai réessayé via Home Assistant de mettre l'adresse Eau du
valenciennois. C'est la sélection de l'adresse qui pose problème au
moment du setup.
En fait, il m'a fallu renseigner mon login et mon mot de passe avant de
coller l'url et de valider. Si je colle l'URL en premier ça
sélectionne automatiquement par défaut l'adresse toutsurmoneau.

Finalement, l'intégration est en place. j'attends de voir si je
récupérerais bien les index de la consommation d'eau 😉

Voilà les logs via le site toutsurmoneau si ça peux aider 😉:

DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:toutsurmoneau.async_client:Calling: donnees-contrats
DEBUG:aiohttp.client:Starting request
<TraceRequestStartParams(method='get', url=URL('
https://www.toutsurmoneau.fr/mon-compte-en-ligne/je-me-connecte'),
headers=<CIMultiDict()>)>
DEBUG:aiohttp.client:Starting request
<TraceRequestStartParams(method='post', url=URL('
https://www.toutsurmoneau.fr/mon-compte-en-ligne/je-me-connecte'),
headers=<CIMultiDict()>)>
DEBUG:toutsurmoneau.async_client:Response: <ClientResponse(
https://www.toutsurmoneau.fr/mon-compte-en-ligne/je-me-connecte) [302
Found]>
<CIMultiDictProxy('Date': 'Mon, 24 Apr 2023 19:54:53 GMT',
'Strict-Transport-Security': 'max-age=2592000; includesubdomains; preload',
'Set-Cookie': 'eZSESSID=cee98ebc215b2218f437f2f252d346e3; expires=Mon,
24-Apr-2023 20:24:53 GMT; Max-Age=1800; path=/; secure; HttpOnly;
SameSite=none', 'Cache-Control': 'no-cache, private', 'Vary':
'cookie,authorization', 'Location': '
https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne/autologin/ire4gcu2Jc9h7GjYNdg5TeqpbZnmR0CXhNpKfYS0cX8/**-**********',
'X-Vhost': 'upgrade_tsme_preview', 'X-Content-Type-Options': 'nosniff',
'X-Frame-Options': 'DENY', 'Content-Type': 'text/html; charset=UTF-8',
'X-Cache': 'MISS', 'Content-Length': '774')>

DEBUG:toutsurmoneau.async_client:Redirect:
https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne/autologin/ire4gcu2Jc9h7GjYNdg5TeqpbZnmR0CXhNpKfYS0cX8/**-**********
DEBUG:aiohttp.client:Starting request
<TraceRequestStartParams(method='get', url=URL('
https://www.toutsurmoneau.fr/mon-compte-en-ligne/donnees-contrats'),
headers=<CIMultiDict()>)>
DEBUG:aiohttp.client:Starting request
<TraceRequestStartParams(method='get', url=URL('
https://www.toutsurmoneau.fr/mon-compte-en-ligne/je-me-connecte'),
headers=<CIMultiDict()>)>
DEBUG:aiohttp.client:Starting request
<TraceRequestStartParams(method='post', url=URL('
https://www.toutsurmoneau.fr/mon-compte-en-ligne/je-me-connecte'),
headers=<CIMultiDict()>)>
DEBUG:toutsurmoneau.async_client:Response: <ClientResponse(
https://www.toutsurmoneau.fr/mon-compte-en-ligne/je-me-connecte) [302
Found]>
<CIMultiDictProxy('Date': 'Mon, 24 Apr 2023 19:54:56 GMT',
'Strict-Transport-Security': 'max-age=2592000; includesubdomains; preload',
'Set-Cookie': 'eZSESSID=bc3152bc91c57d18a6b89283bdbd7b10; expires=Mon,
24-Apr-2023 20:24:56 GMT; Max-Age=1800; path=/; secure; HttpOnly;
SameSite=none', 'Cache-Control': 'no-cache, private', 'Vary':
'cookie,authorization', 'Location': '
https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne/autologin/2SBGwWE0W_w1ncqIgPVcBQxG3SRGYys5MNgbAU2YtaI/**-**********',
'X-Vhost': 'upgrade_tsme_preview', 'X-Content-Type-Options': 'nosniff',
'X-Frame-Options': 'DENY', 'Content-Type': 'text/html; charset=UTF-8',
'X-Cache': 'MISS', 'Content-Length': '774')>

DEBUG:toutsurmoneau.async_client:Redirect:
https://leauduvalenciennois.toutsurmoneau.fr/mon-compte-en-ligne/autologin/2SBGwWE0W_w1ncqIgPVcBQxG3SRGYys5MNgbAU2YtaI/**-**********
DEBUG:aiohttp.client:Starting request
<TraceRequestStartParams(method='get', url=URL('
https://www.toutsurmoneau.fr/mon-compte-en-ligne/donnees-contrats'),
headers=<CIMultiDict()>)>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File
"C:\Users\***\AppData\Local\Programs\Python\Python311\Scripts\toutsurmoneau.exe\__main__.py",
line 7, in <module>
  File
"C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\toutsurmoneau\__main__.py",
line 37, in command_line
    result = asyncio.run(async_execute(args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py",
line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File
"C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py",
line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py",
line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File
"C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\toutsurmoneau\__main__.py",
line 79, in async_execute
    data = await client.async_contracts()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\toutsurmoneau\async_client.py",
line 198, in async_contracts
    contract_list = await self._async_call_api(API_ENDPOINT_CONTRACT)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\toutsurmoneau\async_client.py",
line 168, in _async_call_api
    raise ClientError('Failed refreshing cookie')
toutsurmoneau.errors.ClientError: Failed refreshing cookie

Encore merci

**Comment by laurent-martin** [comment]
Merci pour le retour.

Donc 2 parties:
1- une sorte de bug dans l'interface si on entre d'abord l'adresse puis les user/pass (reset de l'adresse)
2- si on met l'adresse "tutsurmoneau" il y a bien un redirect vers https://leauduvalenciennois.toutsurmoneau.fr/ ... le code pourrait le detecter et utiliser cette adresse. cela serait pas mal. par contre je n'ai pas de compte de la sorte pour tester la redirection...

**Comment by ChtiKev** [comment]
Pour le point 1, c'est bien ça.
Si besoin de tester quelque chose pour le point 2, je veux bien aider.
